#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

find . -type f -name "*.py[co]" -delete
find . -type d -name "__pycache__" -delete

python manage.py migrate
python manage.py runserver_plus 0.0.0.0:8000
