# Generated by Django 2.0.13 on 2019-10-16 10:09

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advert_title', models.CharField(max_length=350)),
                ('url', models.URLField(verbose_name='Url')),
                ('category', models.CharField(choices=[(1, 'Машины'), (2, 'Запчасти'), (3, 'Ремонт и услуги'), (4, 'Коммерческие')], max_length=100)),
                ('sub_category', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('phones', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, help_text='Phone number', max_length=20), size=None)),
                ('characteristics', django.contrib.postgres.fields.jsonb.JSONField()),
                ('description_text', models.TextField()),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
            ],
        ),
    ]
