# Generated by Django 2.0.13 on 2019-10-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Машины'), (2, 'Запчасти'), (3, 'Ремонт и услуги'), (4, 'Коммерческие')]),
        ),
    ]
