# Generated by Django 2.0.13 on 2019-10-17 05:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0002_auto_20191017_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='characteristics',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
