# Generated by Django 2.0.13 on 2019-10-17 09:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0003_auto_20191017_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='characteristics',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
