#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

find . -type f -name "*.py[co]" -delete
find . -type d -name "__pycache__" -delete

python /app/manage.py collectstatic --noinput
python /app/manage.py migrate
python /app/manage.py load_services
/usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app
